/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vipshop.microscope.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum AnnotationType implements org.apache.thrift.TEnum {
  CS(0),
  CR(1),
  SS(2),
  SR(3);

  private final int value;

  private AnnotationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static AnnotationType findByValue(int value) { 
    switch (value) {
      case 0:
        return CS;
      case 1:
        return CR;
      case 2:
        return SS;
      case 3:
        return SR;
      default:
        return null;
    }
  }
}
