// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HtmlTheme.protos

package com.vipshop.microscope.protobuffer;

public final class HtmlThemeProtos {
	private HtmlThemeProtos() {
	}

	public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface HtmlThemeOrBuilder extends com.google.protobuf.MessageOrBuilder {

		// required int32 id = 1;
		/**
		 * <code>required int32 id = 1;</code>
		 */
		boolean hasId();

		/**
		 * <code>required int32 id = 1;</code>
		 */
		int getId();

		// optional string title = 2;
		/**
		 * <code>optional string title = 2;</code>
		 */
		boolean hasTitle();

		/**
		 * <code>optional string title = 2;</code>
		 */
		java.lang.String getTitle();

		/**
		 * <code>optional string title = 2;</code>
		 */
		com.google.protobuf.ByteString getTitleBytes();

		// optional string data = 3;
		/**
		 * <code>optional string data = 3;</code>
		 */
		boolean hasData();

		/**
		 * <code>optional string data = 3;</code>
		 */
		java.lang.String getData();

		/**
		 * <code>optional string data = 3;</code>
		 */
		com.google.protobuf.ByteString getDataBytes();
	}

	/**
	 * Protobuf type {@code com.vipshop.zipkin.pb.HtmlTheme}
	 */
	public static final class HtmlTheme extends com.google.protobuf.GeneratedMessage implements HtmlThemeOrBuilder {
		// Use HtmlTheme.newBuilder() to construct.
		private HtmlTheme(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private HtmlTheme(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private static final HtmlTheme defaultInstance;

		public static HtmlTheme getDefaultInstance() {
			return defaultInstance;
		}

		public HtmlTheme getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private HtmlTheme(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						id_ = input.readInt32();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						title_ = input.readBytes();
						break;
					}
					case 26: {
						bitField0_ |= 0x00000004;
						data_ = input.readBytes();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.vipshop.microscope.protobuffer.HtmlThemeProtos.internal_static_com_vipshop_zipkin_pb_HtmlTheme_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.vipshop.microscope.protobuffer.HtmlThemeProtos.internal_static_com_vipshop_zipkin_pb_HtmlTheme_fieldAccessorTable.ensureFieldAccessorsInitialized(
					com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme.class, com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme.Builder.class);
		}

		public static com.google.protobuf.Parser<HtmlTheme> PARSER = new com.google.protobuf.AbstractParser<HtmlTheme>() {
			public HtmlTheme parsePartialFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new HtmlTheme(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<HtmlTheme> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required int32 id = 1;
		public static final int ID_FIELD_NUMBER = 1;
		private int id_;

		/**
		 * <code>required int32 id = 1;</code>
		 */
		public boolean hasId() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int32 id = 1;</code>
		 */
		public int getId() {
			return id_;
		}

		// optional string title = 2;
		public static final int TITLE_FIELD_NUMBER = 2;
		private java.lang.Object title_;

		/**
		 * <code>optional string title = 2;</code>
		 */
		public boolean hasTitle() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>optional string title = 2;</code>
		 */
		public java.lang.String getTitle() {
			java.lang.Object ref = title_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					title_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string title = 2;</code>
		 */
		public com.google.protobuf.ByteString getTitleBytes() {
			java.lang.Object ref = title_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				title_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string data = 3;
		public static final int DATA_FIELD_NUMBER = 3;
		private java.lang.Object data_;

		/**
		 * <code>optional string data = 3;</code>
		 */
		public boolean hasData() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>optional string data = 3;</code>
		 */
		public java.lang.String getData() {
			java.lang.Object ref = data_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					data_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>optional string data = 3;</code>
		 */
		public com.google.protobuf.ByteString getDataBytes() {
			java.lang.Object ref = data_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
				data_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			id_ = 0;
			title_ = "";
			data_ = "";
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasId()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getTitleBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeBytes(3, getDataBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(1, id_);
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(2, getTitleBytes());
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(3, getDataBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace() throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parseFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code com.vipshop.zipkin.pb.HtmlTheme}
		 */
		public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlThemeOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.vipshop.microscope.protobuffer.HtmlThemeProtos.internal_static_com_vipshop_zipkin_pb_HtmlTheme_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.vipshop.microscope.protobuffer.HtmlThemeProtos.internal_static_com_vipshop_zipkin_pb_HtmlTheme_fieldAccessorTable.ensureFieldAccessorsInitialized(
						com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme.class, com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme.Builder.class);
			}

			// Construct using
			// com.vipshop.zipkin.pb.HtmlThemeProtos.HtmlTheme.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				id_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				title_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				data_ = "";
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.vipshop.microscope.protobuffer.HtmlThemeProtos.internal_static_com_vipshop_zipkin_pb_HtmlTheme_descriptor;
			}

			public com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme getDefaultInstanceForType() {
				return com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme.getDefaultInstance();
			}

			public com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme build() {
				com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme buildPartial() {
				com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme result = new com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.id_ = id_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.title_ = title_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.data_ = data_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme) {
					return mergeFrom((com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme other) {
				if (other == com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme.getDefaultInstance())
					return this;
				if (other.hasId()) {
					setId(other.getId());
				}
				if (other.hasTitle()) {
					bitField0_ |= 0x00000002;
					title_ = other.title_;
					onChanged();
				}
				if (other.hasData()) {
					bitField0_ |= 0x00000004;
					data_ = other.data_;
					onChanged();
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasId()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
				com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.vipshop.microscope.protobuffer.HtmlThemeProtos.HtmlTheme) e.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required int32 id = 1;
			private int id_;

			/**
			 * <code>required int32 id = 1;</code>
			 */
			public boolean hasId() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required int32 id = 1;</code>
			 */
			public int getId() {
				return id_;
			}

			/**
			 * <code>required int32 id = 1;</code>
			 */
			public Builder setId(int value) {
				bitField0_ |= 0x00000001;
				id_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 id = 1;</code>
			 */
			public Builder clearId() {
				bitField0_ = (bitField0_ & ~0x00000001);
				id_ = 0;
				onChanged();
				return this;
			}

			// optional string title = 2;
			private java.lang.Object title_ = "";

			/**
			 * <code>optional string title = 2;</code>
			 */
			public boolean hasTitle() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>optional string title = 2;</code>
			 */
			public java.lang.String getTitle() {
				java.lang.Object ref = title_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					title_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string title = 2;</code>
			 */
			public com.google.protobuf.ByteString getTitleBytes() {
				java.lang.Object ref = title_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
					title_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string title = 2;</code>
			 */
			public Builder setTitle(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				title_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string title = 2;</code>
			 */
			public Builder clearTitle() {
				bitField0_ = (bitField0_ & ~0x00000002);
				title_ = getDefaultInstance().getTitle();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string title = 2;</code>
			 */
			public Builder setTitleBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				title_ = value;
				onChanged();
				return this;
			}

			// optional string data = 3;
			private java.lang.Object data_ = "";

			/**
			 * <code>optional string data = 3;</code>
			 */
			public boolean hasData() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>optional string data = 3;</code>
			 */
			public java.lang.String getData() {
				java.lang.Object ref = data_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					data_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>optional string data = 3;</code>
			 */
			public com.google.protobuf.ByteString getDataBytes() {
				java.lang.Object ref = data_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
					data_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>optional string data = 3;</code>
			 */
			public Builder setData(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				data_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>optional string data = 3;</code>
			 */
			public Builder clearData() {
				bitField0_ = (bitField0_ & ~0x00000004);
				data_ = getDefaultInstance().getData();
				onChanged();
				return this;
			}

			/**
			 * <code>optional string data = 3;</code>
			 */
			public Builder setDataBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000004;
				data_ = value;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:com.vipshop.zipkin.pb.HtmlTheme)
		}

		static {
			defaultInstance = new HtmlTheme(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:com.vipshop.zipkin.pb.HtmlTheme)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_com_vipshop_zipkin_pb_HtmlTheme_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_com_vipshop_zipkin_pb_HtmlTheme_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\020HtmlTheme.protos\022\025com.vipshop.zipkin.p" + "b\"4\n\tHtmlTheme\022\n\n\002id\030\001 \002(\005\022\r\n\005title\030\002 \001("
				+ "\t\022\014\n\004data\030\003 \001(\tB\021B\017HtmlThemeProtos" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_com_vipshop_zipkin_pb_HtmlTheme_descriptor = getDescriptor().getMessageTypes().get(0);
				internal_static_com_vipshop_zipkin_pb_HtmlTheme_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_com_vipshop_zipkin_pb_HtmlTheme_descriptor, new java.lang.String[] { "Id", "Title", "Data", });
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
